-- Add missing columns to products table
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS product_type TEXT,
ADD COLUMN IF NOT EXISTS google_product_category TEXT,
ADD COLUMN IF NOT EXISTS brand TEXT,
ADD COLUMN IF NOT EXISTS condition TEXT,
ADD COLUMN IF NOT EXISTS availability TEXT,
ADD COLUMN IF NOT EXISTS gtin TEXT,
ADD COLUMN IF NOT EXISTS mpn TEXT,
ADD COLUMN IF NOT EXISTS image_link TEXT,
ADD COLUMN IF NOT EXISTS link TEXT;