name: Simple Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    name: Simple Status Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Simple check
        run: echo "This check always passes"